FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PORT=8000

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY frontend ./frontend

RUN python backend/manage.py collectstatic --noinput

EXPOSE $PORT
CMD gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT

